//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleanSchedule
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Floor { get; set; }
        public int Cleaner { get; set; }
    
        public virtual Cleaners Cleaners { get; set; }
    }
}
