//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsInHotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientsInHotel()
        {
            this.ClientsServices = new HashSet<ClientsServices>();
        }
    
        public int ID { get; set; }
        public int Number { get; set; }
        public int Client { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual RoomFond RoomFond { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsServices> ClientsServices { get; set; }
    }
}
