//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsServices
    {
        public int ID { get; set; }
        public int ClientInHotel { get; set; }
        public int Service { get; set; }
    
        public virtual AdditionalServices AdditionalServices { get; set; }
        public virtual ClientsInHotel ClientsInHotel { get; set; }
    }
}
