//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_UP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities _context;

        public Entities()
            : base("name=Entities")
        {
        }

        public static Entities GetContext()
        {
            if ( _context == null )
                _context = new Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalServices> AdditionalServices { get; set; }
        public virtual DbSet<Cleaners> Cleaners { get; set; }
        public virtual DbSet<CleanSchedule> CleanSchedule { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ClientsInHotel> ClientsInHotel { get; set; }
        public virtual DbSet<ClientsServices> ClientsServices { get; set; }
        public virtual DbSet<ReportOfRoomsStatus> ReportOfRoomsStatus { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RoomCategories> RoomCategories { get; set; }
        public virtual DbSet<RoomFond> RoomFond { get; set; }
        public virtual DbSet<RoomPrices> RoomPrices { get; set; }
        public virtual DbSet<RoomStatus> RoomStatus { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
