//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportOfRoomsStatus
    {
        public int ID { get; set; }
        public int Number { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
    
        public virtual RoomFond RoomFond { get; set; }
        public virtual RoomStatus RoomStatus { get; set; }
    }
}
