//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomFond
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomFond()
        {
            this.ClientsInHotel = new HashSet<ClientsInHotel>();
            this.ReportOfRoomsStatus = new HashSet<ReportOfRoomsStatus>();
        }
    
        public int ID { get; set; }
        public int Floor { get; set; }
        public int Number { get; set; }
        public int Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsInHotel> ClientsInHotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportOfRoomsStatus> ReportOfRoomsStatus { get; set; }
        public virtual RoomCategories RoomCategories { get; set; }

        public string NumCategory
        {
            get
            {
                return $"{Number} {RoomCategories.Category}";
            }
        }
    }
}
