//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomPrices
    {
        public int ID { get; set; }
        public int Category { get; set; }
        public int Price { get; set; }
    
        public virtual RoomCategories RoomCategories { get; set; }
    }
}
